### ISSUE TITLE
Subir un documento con la especificacion de su juego

### ISSUE THREAD

**Issue by AlexVazquez-69** [AlexVazquez-69/AlexVazquez-69.github.io#3]
Subir un documento txt. word, ppt, como sea posible.

puede contener imagenes, descripcion de las reglas,etc.

**Comment by DanielAlejandro-5412** [comment]
[Documentacion genero Ritmo .pdf](https://github.com/user-attachments/files/17983874/Documentacion.genero.Ritmo.pdf)
